name: acounts_control
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  custom_navigation_bar: #https://pub.dev/packages/custom_navigation_bar

  cupertino_icons: ^1.0.6
  http: #https://pub.dev/packages/http
  animate_do: #https://pub.dev/packages/animate_do
  flutter_custom_month_picker: #https://pub.dev/packages/flutter_custom_month_picker
  google_fonts: #https://pub.dev/packages/google_fonts
  local_auth: #https://pub.dev/packages/local_auth
  hive: #https://pub.dev/packages/hive
  hive_flutter: #https://pub.dev/packages/hive_flutter
  quickalert: #https://pub.dev/packages/quickalert
  expandable_menu: #https://pub.dev/packages/expandable_menu/example
  board_datetime_picker: #https://pub.dev/packages/board_datetime_picker
  path_provider: #https://pub.dev/packages/path_provider
  share_plus: ^6.3.2
  url_launcher: #https://pub.dev/packages/url_launcher
  material_dialogs: ^1.1.4
  screenshot: #https://pub.dev/packages/screenshot

  firebase_core: #https://pub.dev/packages/firebase_core
  flutter_local_notifications: #https://pub.dev/packages/flutter_local_notifications
  firebase_messaging: ^15.0.1
  shared_preferences: ^2.2.3
  firebase_in_app_messaging: ^0.8.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: #https://pub.dev/packages/intl
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/gifs/
    - assets/js/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
